# Site settings
title:
email:
author:
description:
url: preciseencounter.github.io
baseurl: /TestDeploy

# Build settings
permalink: /:title
sass:
  sass_dir: css
collections:
  works:
    output: true
    permalink: /works/:title
  publications:
    output: true
    permalink: /publications/:title
